[package]
name = "rns-loot-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
csv = "1.4.0"
rand = "0.9.2"
serde = "1.0.228"
